# Site settings
title: Alper Kalaycioglu
email: f/xgeraadb
url: https://github.com/alperkal
description: "Alper Kalaycioglu"
keywords: "Software Engineer, Kubernetes, Software Architecture"
skills: "Software Engineer"
meta_author: Kalaycioglu Alper

# Google webmaster tools
google_verify:
google_analytics: G-J1HSHLLRJ9
google_tag_manager: GTM-MSJ39RP
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static
contact: none

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Alper Kalaycioglu
  location: 
  social: 
  credits: 

about:
  column1: I'm a father of two kids, two cats and at the same time a software engineer. I'm particularly interested in resilient systems, software architecture and microservices.
  column2: I had experience in different stacks over the 20 years and my main working stack is Kotlin and Spring Boot. (Although I still prefer Python and C in my personal projects)
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/alperkal
  - title: facebook
    url: https://www.facebook.com/alperkal
  - title: instagram
    url: http://instagram.com/alperkal
  - title: linkedin
    url: http://linkedin.com/alperkal
  - title: github
    url: http://github.com/alperkal

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
